### ISSUE TITLE
Can't build with latest llvm-22

### ISSUE THREAD

**Issue by data-man** [c3lang/c3c#2666]
```
c3c/src/compiler/llvm_codegen_function.c:632:28: error: 'LLVMStructType' is deprecated: Use of the global context is deprecated, use LLVMStructTypeInContext instead [-Werror,-Wdeprecated-declarations]
  632 |                 LLVMTypeRef entry_type = LLVMStructType(types, 3, false);
      |                                          ^
/usr/lib/llvm-22/include/llvm-c/Core.h:1579:12: note: 'LLVMStructType' has been explicitly marked deprecated here
 1579 | LLVM_C_ABI LLVM_ATTRIBUTE_C_DEPRECATED(
      |            ^
/usr/lib/llvm-22/include/llvm-c/Deprecated.h:26:23: note: expanded from macro 'LLVM_ATTRIBUTE_C_DEPRECATED'
   26 |   decl __attribute__((deprecated(message)))
      |                       ^
1 error generated.
```

```sh
$ apt info llvm-22
Package: llvm-22
Version: 1:22~++20251220083013+ab665f217ac5-1~exp1~20251220083135.281
```
The quick fix: add `-Wno-deprecated-declarations` to `CMakeLists.txt`.

**Comment by lerno** [comment]
That was a serious problem. Fixing it now.

**Comment by lerno** [comment]
This should be fixed now.

**Comment by data-man** [comment]
And another error:
```
src/compiler/llvm_codegen_module.c:180:22: error: 'LLVMCreateBuilder' is deprecated: Use of the global context is deprecated, use LLVMCreateBuilderInContext instead [-Werror,-Wdeprecated-declarations]
  180 |         c->global_builder = LLVMCreateBuilder();
      |                             ^
/usr/lib/llvm-22/include/llvm-c/Core.h:4470:1: note: 'LLVMCreateBuilder' has been explicitly marked deprecated here
 4470 | LLVM_ATTRIBUTE_C_DEPRECATED(LLVMBuilderRef LLVMCreateBuilder(void),
      | ^
/usr/lib/llvm-22/include/llvm-c/Deprecated.h:26:23: note: expanded from macro 'LLVM_ATTRIBUTE_C_DEPRECATED'
   26 |   decl __attribute__((deprecated(message)))
      |                       ^
1 error generated.
```

**Comment by lerno** [comment]
Is this still happening @data-man ?

**Comment by data-man** [comment]
> Is this still happening [@data-man](https://github.com/data-man) ?

Yes:
```
c3c/src/compiler/llvm_codegen_module.c:180:22: error: 'LLVMCreateBuilder' is deprecated: Use of the global context is deprecated, use LLVMCreateBuilderInContext instead [-Werror,-Wdeprecated-declarations]
  180 |         c->global_builder = LLVMCreateBuilder();
      |                             ^
/usr/lib/llvm-22/include/llvm-c/Core.h:4470:1: note: 'LLVMCreateBuilder' has been explicitly marked deprecated here
 4470 | LLVM_ATTRIBUTE_C_DEPRECATED(LLVMBuilderRef LLVMCreateBuilder(void),
      | ^
/usr/lib/llvm-22/include/llvm-c/Deprecated.h:26:23: note: expanded from macro 'LLVM_ATTRIBUTE_C_DEPRECATED'
   26 |   decl __attribute__((deprecated(message)))
      |                       ^
1 error generated.
```

However, a link error has recently appeared (with `-Wno-deprecated-declarations` option):
```
/usr/bin/ld: /usr/lib/llvm-22/lib/liblldCOFF.a(LTO.cpp.o): in function `lld::coff::BitcodeCompiler::BitcodeCompiler(lld::coff::COFFLinkerContext&)':
(.text._ZN3lld4coff15BitcodeCompilerC2ERNS0_17COFFLinkerContextE+0x51d): undefined reference to `vtable for llvm::lto::DTLTO'
/usr/bin/ld: /usr/lib/llvm-22/lib/liblldELF.a(LTO.cpp.o): in function `lld::elf::BitcodeCompiler::BitcodeCompiler(lld::elf::Ctx&)':
(.text._ZN3lld3elf15BitcodeCompilerC2ERNS0_3CtxE+0x9fb): undefined reference to `vtable for llvm::lto::DTLTO'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Command exited with non-zero status 1
```

**Comment by lerno** [comment]
Fixed, please try now.

**Comment by data-man** [comment]
Thank you!
As I can see in CI, compilation was successful with LLVM-22.  
But I still have the linking error above.   
It's likely that this is my local problem.

**Comment by ManuLinares** [comment]
> Thank you! As I can see in CI, compilation was successful with LLVM-22. But I still have the linking error above. It's likely that this is my local problem.

Hi, can you tell me you build environment?
It would be helpful for catching this in CI.

**Comment by data-man** [comment]
> Hi, can you tell me you build environment?

I'm on Devuan/Ceres (== Debian/sid without systemd).
The `apt.llvm.org/unstable` packages weren't updated for a while, so I switched to `apt.llvm.org/trixie`.

Today I switched back to `unstable`, but the linking error still persists.

**Comment by ManuLinares** [comment]
This PR should fix this:
https://github.com/c3lang/c3c/pull/2987

**Comment by data-man** [comment]
```
[5/98] Generating git_hash.h
Git Hash: cdc3db0da99735b7d5e7edb922988856c58c1ef0
[88/98] Building C object CMakeFiles/c3c.dir/src/compiler/llvm_codegen_expr.c.o
FAILED: [code=1] CMakeFiles/c3c.dir/src/compiler/llvm_codegen_expr.c.o
/usr/bin/clang -DC3_LINK_CURL -DLLVM_AVAILABLE=1 -DTB_AVAILABLE=0 -D_GLIBCXX_USE_CXX11_ABI=1 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/usr/lib/llvm-23/include -I/home/data1/Repos/Git/C3/-From_c3lang/c3c/src -I/home/data1/Repos/Git/C3/-From_c3lang/c3c/build-rel -I/home/data1/Repos/Git/C3/-From_c3lang/c3c/wrapper/include -I/home/data1/Repos/Git/C3/-From_c3lang/c3c/dependencies/miniz -isystem /usr/include/libxml2 -O3 -DNDEBUG -std=gnu11 -gdwarf-3 -fno-exceptions -pthread -Wall -Werror -Wno-unknown-pragmas -Wno-unused-result -Wno-unused-function -Wno-unused-variable -Wno-unused-parameter -Wno-char-subscripts -MD -MT CMakeFiles/c3c.dir/src/compiler/llvm_codegen_expr.c.o -MF CMakeFiles/c3c.dir/src/compiler/llvm_codegen_expr.c.o.d -o CMakeFiles/c3c.dir/src/compiler/llvm_codegen_expr.c.o -c /home/data1/Repos/Git/C3/-From_c3lang/c3c/src/compiler/llvm_codegen_expr.c
/home/data1/Repos/Git/C3/-From_c3lang/c3c/src/compiler/llvm_codegen_expr.c:1350:77: error: use of undeclared identifier 'LLVMBr'; did you mean 'LLVMOr'?
 1350 |         if (!LLVMIsAInstruction(maybe_br) || LLVMGetInstructionOpcode(maybe_br) != LLVMBr) return;
      |                                                                                    ^~~~~~
      |                                                                                    LLVMOr
/usr/lib/llvm-23/include/llvm-c/Core.h:96:3: note: 'LLVMOr' declared here
   96 |   LLVMOr             = 24,
      |   ^
1 error generated.
```

**Comment by ManuLinares** [comment]
Could you post your system info and relevant software versions?

**Comment by lerno** [comment]
Please open a new issue for this, since the last one was fixed.
